### ISSUE TITLE
🐛 Donation tickets doesn't include taxes

### ISSUE THREAD

**Issue by elronalds** [HiEventsDev/Hi.Events#101] opened 2024-07-16 12:03 UTC
**Describe the bug**
When using the donation ticket option and you have the "Include tax and fees in the price" setting selected the taxes are not included. 

**To Reproduce**
1. Setup a donation ticket
2. Set the event setting for "Include tax and fees in the price" to selected
3. Apply the tax type to this ticket, for example 10%
5. Process a test payment and the customer will be charged $5.50 for the transaction
6. The tax isn't included in the price

**Expected behavior**
The tax should be included in the $5 and the customer shouldn't be charged $5.50

**Hi.Events Version and platform**
Docker, unsure how to check the version.  Is there a version number stored somewhere in the code.  I completed a serach on Github and couldn't locate this.

**Comment by daveearley** [comment] 2024-07-17 04:56
Thanks for the report @elronalds!

This is by design. Enabling `Include tax and fees in the price` will include the taxes on top of the $5. The setting only affects how the price is displayed.

**Comment by elronalds** [comment] 2024-07-17 10:25
@daveearley So how would you configure this so the customer is only charged $5 and that includes the 10% tax?

**Comment by daveearley** [comment] 2024-07-18 03:54
The price is assumed to be pre-tax when you create the ticket. So you would set a price of 4.55 and then add the 10% tax.

The UI around this could definitely be improved. As a first step I'll update the UI in the ticket creation model to show the price including tax under the price input.

**Comment by daveearley** [comment] 2024-08-23 04:19
Closing this, as the feature will be tracked in #128.

**Closed by daveearley** 2024-08-23 04:19 UTC
Labels: bug
