### ISSUE TITLE
🐛organiser can create new organisers

### ISSUE THREAD

**Issue by justynpride** [HiEventsDev/Hi.Events#137] opened 2024-08-10 07:54 UTC
**Describe the bug**
A user with the organiser permission level has access to the new organiser option on the dashboard. 
This may not be a bug, but my lack of understanding of the logic for how organisers work.

**To Reproduce**
1. Go to 'manage/events'
2. Click on 'create new'
3. See 'create new organiser' as an option

**Expected behavior**
I was assuming this level of permission was to create and manage events only? 

**Screenshots**
![image](https://github.com/user-attachments/assets/47c9f025-af9f-413c-9aa5-48c92c1937fa)

**Hi.Events Version and platform**
0.5.0-alpha.2

**Comment by daveearley** [comment] 2024-08-11 01:23
Thanks for the report!

This is by design. Currently the only difference between admins and organizers is that admins can manage payment information, users, and account settings.

There are to limit users to certain organizers and events. This will be added in the near future.

**Comment by justynpride** [comment] 2024-08-11 17:51
That makes a lot of sense, especially as there is extra functionality to come in the future which will provide more granular control.

**Comment by daveearley** [comment] 2024-08-23 04:01
Closing this as it's [mapped to a feature](https://github.com/orgs/HiEventsDev/projects/1?pane=issue&itemId=74372916). It should be included in a release soon.

**Closed by daveearley** 2024-08-23 04:01 UTC
Labels: bug
